export const ADD_WORD_START = "ADD_WORD_START";
export const ADD_WORD_SUCCESS = "ADD_WORD_SUCCESS";
export const ADD_WORD_ERROR = "ADD_WORD_ERROR";

export const ADD_COMMENT_START = "ADD_COMMENT_START";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_START";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_START";

export const REPORT_WORD_START = "REPORT_WORD_START";
export const REPORT_WORD_SUCCESS = "REPORT_WORD_SUCCESS";
export const REPORT_WORD_ERROR = "REPORT_WORD_ERROR";

export const SEARCH_WORD_START = "SEARCH_WORD_START";
export const SEARCH_WORD_SUCCESS = "SEARCH_WORD_SUCCESS";
export const SEARCH_WORD_ERROR = "SEARCH_WORD_ERROR";

export const ADD_WORD_PRONUNCIATION_START = "ADD_WORD_PRONUNCIATION_START";
export const ADD_WORD_PRONUNCIATION_SUCCESS = "ADD_WORD_PRONUNCIATION_SUCCESS";
export const ADD_WORD_PRONUNCIATION_ERROR = "ADD_WORD_PRONUNCIATION_ERROR";
